"""More built-in art, all on one shared palette (see the pixel-art skill).

Letters: k outline, K/s/S/w greys to white, q/g/G/l greens, n/b/B/e browns,
r/R/p/P reds to pink, O orange, y/Y yellows, u/U/c/C blues, v/V/m purples,
t/T teals. "." is see-through. Everything faces right.
"""

PAL = {
    "k": "#1a1c2c", "K": "#333c57", "s": "#566c86", "S": "#94b0c2", "w": "#f4f4f4",
    "q": "#1e4a3a", "g": "#257953", "G": "#38b764", "l": "#a7f070",
    "n": "#3d2a24", "b": "#6e4a30", "B": "#a8703c", "e": "#e8c48c",
    "r": "#8c2a3a", "R": "#d6404e", "p": "#ff8a9a", "P": "#ffcdd2",
    "O": "#ef7d3a", "y": "#ffcd4f", "Y": "#fff1a8",
    "u": "#29366f", "U": "#3b5dc9", "c": "#41a6f6", "C": "#73eff7",
    "v": "#4b2a6b", "V": "#8a4fc0", "m": "#d69cf2",
    "t": "#1f6f73", "T": "#3fb8a8",
}


def pet(id, name, behavior, frames, speed=1.0):
    return {"id": id, "name": name, "kind": "pet", "behavior": behavior,
            "palette": PAL, "frames": frames, "speed": speed}


def deco(id, name, frames, behavior="stay"):
    return {"id": id, "name": name, "kind": "deco", "behavior": behavior,
            "palette": PAL, "frames": frames}


PACK = [
    # ---------------------------------------------------------------- pets
    pet("bunny", "Bunny", "hop", [
        [
            "......k.k...",
            ".....kpkpk..",
            ".....kpkpk..",
            ".....kwkwk..",
            "....kwwwwwk.",
            "....kwwwkwwk",
            ".kk.kwwwwwpk",
            "kwwkkwwwwwk.",
            "kwwwwwwwwk..",
            "kSwwwwwwSk..",
            ".kSSwwSSk...",
            "..kkkkkkk...",
        ],
        [
            "......k.k...",
            ".....kpkpk..",
            ".....kpkpk..",
            ".....kwkwk..",
            "....kwwwwwk.",
            "....kwwwkwwk",
            ".kk.kwwwwwpk",
            "kwwkkwwwwwk.",
            "kwwwwwwwwk..",
            "kSwwwwwwSk..",
            "kSSk.kSSk...",
            "kkk..kkk....",
        ],
    ]),
    pet("frog", "Frog", "hop", [
        [
            "...kkk.kkk..",
            "..kwwkGkwwk.",
            "..kwkkGkwkk.",
            ".kGGGGGGGGk.",
            "kGlGGGGGGGGk",
            "kGGGGGGRRRGk",
            "kgGGGGGGGGgk",
            "kgYYYYYYYYgk",
            ".kggk..kggk.",
            "kkkk....kkkk",
        ],
        [
            "............",
            "...kkk.kkk..",
            "..kwwkGkwwk.",
            "..kwkkGkwkk.",
            ".kGGGGGGGGk.",
            "kGlGGGGGGGGk",
            "kGGGGGGRRRGk",
            "kgGYYYYYYGgk",
            "kgkk....kkgk",
            "kk........kk",
        ],
    ]),
    pet("duck", "Duck", "walk", [
        [
            "......kkkk..",
            ".....kyyyyk.",
            ".....kyykyk.",
            ".....kyyyyOO",
            "k....kyyyyk.",
            "kk..kyyyyk..",
            "kykkyyyyyyk.",
            "kyyyyYYyyyk.",
            ".kyyYYYYyk..",
            "..kkkkkkk...",
            "....kO.kO...",
            "...kOO.kOO..",
        ],
        [
            "......kkkk..",
            ".....kyyyyk.",
            ".....kyykyk.",
            ".....kyyyyOO",
            "k....kyyyyk.",
            "kk..kyyyyk..",
            "kykkyyyyyyk.",
            "kyyyyYYyyyk.",
            ".kyyYYYYyk..",
            "..kkkkkkk...",
            ".....kOkO...",
            "....kOOkOO..",
        ],
    ]),
    pet("chick", "Chick", "walk", [
        [
            "...kkkk..",
            "..kYYYYk.",
            ".kYYYkYk.",
            ".kYYYYYOO",
            "kYYYyYYk.",
            "kYYyyYYk.",
            "kYYYYYYk.",
            ".kkkkkk..",
            "..O..O...",
        ],
        [
            "...kkkk..",
            "..kYYYYk.",
            ".kYYYkYk.",
            ".kYYYYYOO",
            "kYYYyYYk.",
            "kYYyyYYk.",
            "kYYYYYYk.",
            ".kkkkkk..",
            "...O.O...",
        ],
    ], speed=0.8),
    pet("dog", "Dog", "walk", [
        [
            "..........kk....",
            ".........kbbkk..",
            ".........kBBBBk.",
            "k........kBkBBBk",
            "kBk......kBBBBkk",
            ".kBk.kkkkbBBBBk.",
            "..kkBBBBBBBkkk..",
            "..kBBeeeeBBk....",
            "..kBBBBBBBBk....",
            "..kBk.kBk.kBk...",
            "..kk..kk..kk....",
        ],
        [
            "..........kk....",
            ".........kbbkk..",
            ".........kBBBBk.",
            ".........kBkBBBk",
            "k........kBBBBkk",
            "kBk..kkkkbBBBBk.",
            ".kkkBBBBBBBkkk..",
            "..kBBeeeeBBk....",
            "..kBBBBBBBBk....",
            ".kBk..kBk..kBk..",
            ".kk...kk...kk...",
        ],
    ]),
    pet("penguin", "Penguin", "walk", [
        [
            "...kkkk...",
            "..kKKKKk..",
            ".kKKwKwKk.",
            ".kKKwwwOO.",
            "kKKwwwwwk.",
            "kKkwwwwwk.",
            "kKkwwwwwk.",
            "kKKwwwwwk.",
            ".kKwwwwk..",
            "..kkkkk...",
            "..OO.OO...",
        ],
        [
            "...kkkk...",
            "..kKKKKk..",
            ".kKKwKwKk.",
            ".kKKwwwOO.",
            "kKKwwwwwk.",
            "kKKkwwwwk.",
            "kKKkwwwwk.",
            "kKKwwwwwk.",
            ".kKwwwwk..",
            "..kkkkk...",
            ".OO...OO..",
        ],
    ], speed=0.6),
    pet("crab", "Crab", "walk", [
        [
            ".kk......kk.",
            "kRRk....kRRk",
            "kRk......kRk",
            ".kRk.kk.kRk.",
            "..kkwkkwkk..",
            ".kRRRRRRRRk.",
            "kRpRRRRRRRRk",
            "kRRRRRRRRRRk",
            ".krrrrrrrrk.",
            "k.k.k..k.k.k",
        ],
        [
            ".kk......kk.",
            "kRRk....kRRk",
            "kRk......kRk",
            ".kRk.kk.kRk.",
            "..kkwkkwkk..",
            ".kRRRRRRRRk.",
            "kRpRRRRRRRRk",
            "kRRRRRRRRRRk",
            ".krrrrrrrrk.",
            ".k.k.kk.k.k.",
        ],
    ], speed=0.7),
    pet("turtle", "Turtle", "walk", [
        [
            "....kkkkk.......",
            "...kgGGGgk......",
            "..kgGlGGGgk.kkk.",
            ".kgGGGgGGGgkGGGk",
            ".kgGGgGgGGgkGkGk",
            "kggggggggggkGGGk",
            "kkkkkkkkkkkkkkk.",
            ".kGGk....kGGk...",
            ".kkk.....kkk....",
        ],
        [
            "....kkkkk.......",
            "...kgGGGgk......",
            "..kgGlGGGgk.kkk.",
            ".kgGGGgGGGgkGGGk",
            ".kgGGgGgGGgkGkGk",
            "kggggggggggkGGGk",
            "kkkkkkkkkkkkkkk.",
            "..kGGk..kGGk....",
            "..kkk...kkk.....",
        ],
    ], speed=0.35),
    pet("snail", "Snail", "walk", [
        [
            "...kkkk.......",
            "..kVmmVk..k.k.",
            ".kVmVVmVk.kek.",
            ".kVmkVmVk.kek.",
            ".kVmVVmVk.keek",
            "..kVVVVkkeekek",
            "kkeeeeeeeeeek.",
            "keeeeeeeeeek..",
            ".kkkkkkkkkk...",
        ],
        [
            "...kkkk.......",
            "..kVmmVk...k.k",
            ".kVmVVmVk..kek",
            ".kVmkVmVk.keek",
            ".kVmVVmVk.keek",
            "..kVVVVkkeekek",
            "keeeeeeeeeeek.",
            "keeeeeeeeeek..",
            ".kkkkkkkkkk...",
        ],
    ], speed=0.25),
    pet("bee", "Bee", "fly", [
        [
            "...kk.kk...",
            "..kCCkCCk..",
            "..kCCkCCk..",
            ".kkykkkykk.",
            "kyykyykyykk",
            "kyykyykykwk",
            "kyykyykyyk.",
            ".kkkkkkkk..",
        ],
        [
            "...........",
            "...........",
            "..kkk.kkk..",
            ".kCCkkkCCk.",
            "kyykyykyykk",
            "kyykyykykwk",
            "kyykyykyyk.",
            ".kkkkkkkk..",
        ],
    ]),
    pet("butterfly", "Butterfly", "fly", [
        [
            ".kkk...kkk.",
            "kmVVk.kVVmk",
            "kVmmVkVmmVk",
            "kVVmVkVmVVk",
            ".kVVkkkVVk.",
            ".kmVkkkVmk.",
            ".kVVk.kVVk.",
            "..kk...kk..",
        ],
        [
            "...........",
            "...........",
            "..kk...kk..",
            ".kmVk.kVmk.",
            ".kVmVkVmVk.",
            "..kVkkkVk..",
            "...kkkkk...",
            "...........",
        ],
    ], speed=0.7),
    pet("ghost", "Ghost", "swim", [
        [
            "...kkkk...",
            "..kwwwwk..",
            ".kwwwwwwk.",
            ".kwwkwkwk.",
            "kwwwwwwwwk",
            "kwwwwwPwwk",
            "kSwwwwwwwk",
            "kSSwwwwwSk",
            "kSkSwSkSSk",
            "kk.kk.kk.k",
        ],
        [
            "...kkkk...",
            "..kwwwwk..",
            ".kwwwwwwk.",
            ".kwwkwkwk.",
            "kwwwwwwwwk",
            "kwwwwwPwwk",
            "kSwwwwwwwk",
            "kSSwwwwwSk",
            "kSSkSwSkSk",
            "k.kk.kk.kk",
        ],
    ], speed=0.6),
    pet("jelly", "Jellyfish", "swim", [
        [
            "...kkkk...",
            "..kmmmmk..",
            ".kmPmmmmk.",
            "kmPmmmmmmk",
            "kmmmmmmmmk",
            "kkkkkkkkkk",
            ".m.m..m.m.",
            ".m..m.m..m",
            "m..m..m.m.",
            ".m.m...m..",
        ],
        [
            "..........",
            "...kkkk...",
            "..kmmmmk..",
            ".kmPmmmmk.",
            "kmPmmmmmmk",
            "kkkkkkkkkk",
            "m.m..m.m..",
            ".m.m.m..m.",
            ".m..m.m..m",
            "m...m..m..",
        ],
    ], speed=0.5),
    pet("puffer", "Pufferfish", "swim", [
        [
            "...k.k.k...",
            "..kykykyk..",
            ".kyyyyyyyk.",
            "kyyYYyywkyk",
            "kyYYyyykkyk",
            "kyyyyyyyyyO",
            "kyyyYYYyyyk",
            ".kyyyyyyyk.",
            "..kykykyk..",
            "...k.k.k...",
        ],
        [
            "...........",
            "...k.k.k...",
            "..kykykyk..",
            "kkyyyyywkyk",
            "kyYYyyykkyk",
            "kyyyyyyyyyO",
            "kkyyYYYyyyk",
            "..kykykyk..",
            "...k.k.k...",
            "...........",
        ],
    ], speed=0.6),

    # -------------------------------------------------------------- decor
    deco("cactus", "Cactus", [[
        ".....kk.....",
        "....kGlk....",
        "....kGGk....",
        ".kk.kGlk....",
        "kGGkkGGk.kk.",
        "kGlkkGlkkGGk",
        "kGGGGGGkkGlk",
        ".kkkkGlGGGGk",
        "....kGGkkkk.",
        "....kGlk....",
        "..kkkkkkkk..",
        "..kBBBBBBk..",
        "...kbbbbk...",
        "...kkkkkk...",
    ]]),
    deco("sunflower", "Sunflower", [[
        "...kkkk...",
        "..kyYYyk..",
        ".kyybbyyk.",
        "kyYbnnbyyk",
        "kyybnnbyyk",
        ".kyybbyyk.",
        "..kyyyyk..",
        "...kkGk...",
        ".kk.kGk...",
        "kGlkkGk...",
        ".kGGGGk.kk",
        "....kGkkGk",
        "....kGGGk.",
        "....kGk...",
        "....kgk...",
    ]]),
    deco("tulips", "Tulips", [[
        ".k.k...k.k..",
        "kRkRk.kmkmk.",
        "kRRRk.kmmmk.",
        ".kRk...kmk..",
        "..G..k..G...",
        "..G.kyk.G...",
        "..GGkYkGG...",
        ".lGG.G.Gl...",
        "..G..G.G....",
        ".kkkkkkkkkk.",
    ]]),
    deco("stump", "Stump", [[
        "..kkkkkkk...",
        ".keBBeeBek..",
        "keBeeBBeeBk.",
        "kbeBBBBBebk.",
        "kbkeeeeekbk.",
        "kbbbBbbbbbk.",
        "kbbBbbbBbbk.",
        "kbbBbbbBbbkk",
        "kbbbbbBbbbbk",
        "knnnnnnnnnnk",
    ]]),
    deco("fence", "Fence", [[
        "..k......k......",
        ".kek....kek.....",
        ".kek....kek.....",
        "kkekkkkkkekkkkkk",
        "eeeeeeeeeeeeeeee",
        "kkBkkkkkkBkkkkkk",
        ".kek....kek.....",
        "kkekkkkkkekkkkkk",
        "eeeeeeeeeeeeeeee",
        "kkBkkkkkkBkkkkkk",
        ".kek....kek.....",
        ".kBk....kBk.....",
    ]]),
    deco("sign", "Signpost", [[
        "kkkkkkkkkkk.",
        "keeeeeeeeeek",
        "keBBkBkBBek.",
        "keeeeeeeeeek",
        "kBBBBBBBBBk.",
        "kkkkkbkkkkk.",
        ".....bk.....",
        ".....bk.....",
        ".....bk.....",
        "....kbbk....",
    ]]),
    deco("campfire", "Campfire", [
        [
            ".....k......",
            "....kRk.....",
            "...kROk.k...",
            "...kOyRkRk..",
            "..kROyyORk..",
            "..kOyYYyOk..",
            "..kOyYYyOk..",
            ".kkbkOOkbkk.",
            "kBbbBkkBbbBk",
            "ksskkBBkkssk",
            ".kkkkkkkkkk.",
        ],
        [
            "......k.....",
            ".....kRk....",
            "..k..kORk...",
            ".kRk.kROk...",
            "..kROyyORk..",
            "..kOyYyyOk..",
            "..kOyYYyOk..",
            ".kkbkOOkbkk.",
            "kBbbBkkBbbBk",
            "ksskkBBkkssk",
            ".kkkkkkkkkk.",
        ],
    ]),
    deco("lamp", "Lamp post", [[
        "...kkk...",
        "..kKKKk..",
        ".kKKKKKk.",
        ".kYyYyYk.",
        ".kyYYYyk.",
        ".kYyYyYk.",
        "..kkkkk..",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "..kKKKk..",
        ".kKKKKKk.",
    ]]),
    deco("cherry", "Cherry tree", [[
        ".....kkkkk......",
        "...kkPPpPPkk....",
        "..kPPwPPPPpPk...",
        ".kPwPPPpPPPPPk..",
        ".kPPPPPPPwPPpk..",
        "kpPPpPPPPPPPPPk.",
        "kPPPPPwPPpPPPPk.",
        "kpPPPPPPPPPPPpk.",
        ".kppPPPpPPPPpk..",
        "..kkppkbkppkk...",
        "....kkkbkk......",
        "......kbbk......",
        "......kbbk......",
        "......kbbk......",
        ".....kbbbbk.....",
        "....kbbkkbbk....",
    ]]),
    deco("palm", "Palm tree", [[
        ".....kkkk.......",
        "...kkGGGGkkk....",
        "..kGGlGGGGGGk...",
        ".kGGkkGGkkGGGk..",
        "kGGk..kBBkkkGGk.",
        "kGk...kBk...kGk.",
        "kk....kBk....kk.",
        ".......kBk......",
        ".......kBk......",
        "........kBk.....",
        "........kBk.....",
        "........kBk.....",
        ".......kBBk.....",
        "......kBbBBk....",
    ]]),
    deco("coral", "Coral", [[
        "..k.....k...",
        ".kpk...kpk..",
        ".kpk.k.kpk.k",
        ".kpkkpkkpkkp",
        "k.kpkpkpkkpk",
        "kpkpkpkpk.kp",
        ".kpppppkkpk.",
        "..kpRRpppk..",
        "...kRRRpk...",
        "....kRRk....",
        "..kkkRRkkk..",
    ]]),
    deco("chest", "Treasure chest", [[
        "..kkkkkkkkk...",
        ".kBBBBBBBBBk..",
        "kBByyyyyyyBBk.",
        "kBBBBBBBBBBBk.",
        "kkkkkkykkkkkk.",
        "kbBBBkYykBBbk.",
        "kbBBBkkkBBBbk.",
        "kbBBBBBBBBBbk.",
        "knnnnnnnnnnnk.",
        ".kkkkkkkkkkk..",
    ]]),
    deco("crystal", "Crystals", [[
        ".....k......",
        "....kCk.....",
        "...kCwck....",
        "...kCcck....",
        ".k.kCcck.k..",
        "kCkkCccckmk.",
        "kCwkCcckVmk.",
        "kcckCccckVmk",
        "kcckcuucVVVk",
        "kkkkkkkkkkkk",
    ]]),
    deco("pumpkin", "Pumpkin", [[
        ".....kk.....",
        "....kgk.....",
        "..kkkkkkkk..",
        ".kOyOkOOyOk.",
        "kOyOOkOyOOOk",
        "kOyOOkOyOOOk",
        "kOOOOkOOOOOk",
        "kOOOrkOOOOrk",
        ".krrrkrrrrk.",
        "..kkkkkkkk..",
    ]]),
    deco("cottage", "Cottage", [[
        "............kkk...",
        "......kk....kKk...",
        "....kkRRkk..kKk...",
        "..kkRRRRRRkkkKk...",
        ".kRRRRRRRRRRRkk...",
        "kRRRRRRRRRRRRRRk..",
        "krrrrrrrrrrrrrrrk.",
        ".keeeeeeeeeeeek...",
        ".keUUkeeeekBBkek..",
        ".kecCkeeeekBBkek..",
        ".keeeeeeeekBBkek..",
        ".keeeeeeeekByBek..",
        ".kBBBBBBBBkBBkBk..",
        ".kkkkkkkkkkkkkkk..",
    ]]),
    deco("cloud", "Cloud", [[
        ".....kkkk.......",
        "...kkwwwwkk.....",
        "..kwwwwwwwwkkk..",
        ".kwwwwwwwwwwwwk.",
        "kwwwwwwwwwwwwwwk",
        "kSwwwwwwwwwwwwSk",
        ".kSSSwwwwwwSSSk.",
        "..kkkkkkkkkkkk..",
    ]], behavior="stay"),
    deco("pond", "Pond", [[
        "....kkkkkkkk....",
        "..kkcCccccCcckk.",
        ".kcCccGkcccccCck",
        "kcccckGGkcwccccck"[:16],
        "kcccUccccccccUck",
        ".kUcccccUccccUk.",
        "..kkUUUUUUUUkk..",
        "....kkkkkkkk....",
    ]]),
]


def _witch_cat(cat_rows):
    """The cat, recoloured slate grey with yellow eyes, wearing a witch hat.
    (v0.5: lighter than black, so it doesn't vanish on dark wallpapers.)"""
    recolour = str.maketrans({"c": "s", "C": "S", "e": "y"})
    hat = [
        "............k...",
        "...........kVk..",
        "..........kVVVk.",
        "..........kOOOk.",
        ".........kvvvvvk",
    ]
    return hat + [r.translate(recolour) for r in cat_rows[2:]]


_CAT = [
    [
        "..........k...k.",
        "k.........kk.kk.",
        "kc........kcccck",
        ".kc.......kcecek",
        ".kc.kkkkkkkCCpCk",
        "..kccccccccckkk.",
        "..kcCcccCcccck..",
        "..kcccccccccck..",
        "...kck.kck.kck..",
        "...kk..kk..kk...",
    ],
    [
        "..........k...k.",
        "..........kk.kk.",
        "k.........kcccck",
        "kc........kcecek",
        ".kc.kkkkkkkCCpCk",
        "..kccccccccckkk.",
        "..kcCcccCcccck..",
        "..kcccccccccck..",
        "..kck..kck..kck.",
        "..kk...kk....kk.",
    ],
]

# The Halloween set ("set": shown together on the board, at the top in October).
HALLOWEEN = [
    dict(pet("bat", "Bat", "fly", [
        [
            "k............k",
            "Vk...k..k...kV",
            "vVk..kkkk..kVv",
            ".vVkkvyvykkVv.",
            "..vvkvvvvkvv..",
            "....kkvvkk....",
            "......kk......",
            "..............",
        ],
        [
            "..............",
            ".....k..k.....",
            ".....kkkk.....",
            "....kvyvyk....",
            "..kkkvvvvkkk..",
            ".kVvvkvvkvvVk.",
            "kVv..kkkk..vVk",
            "k............k",
        ],
    ], speed=1.1), set="halloween"),
    dict(pet("witchcat", "Witch cat", "walk", [_witch_cat(f) for f in _CAT]), set="halloween"),
    dict(deco("jack", "Jack-o'-lantern", [
        [
            ".....kgk....",
            "..kkkkkkkk..",
            ".kOOOkkOOOk.",
            "kOyyOOOOyyOk",
            "kOOyOOOOyOOk",
            "kOOOOOOOOOOk",
            "kOyOyyyyOyOk",
            "kOOyyOOyyOOk",
            ".krrOOOOrrk.",
            "..kkkkkkkk..",
        ],
        [
            ".....kgk....",
            "..kkkkkkkk..",
            ".kOOOkkOOOk.",
            "kOYYOOOOYYOk",
            "kOOYOOOOYOOk",
            "kOOOOOOOOOOk",
            "kOYOYYYYOYOk",
            "kOOYYOOYYOOk",
            ".krrOOOOrrk.",
            "..kkkkkkkk..",
        ],
    ]), set="halloween"),
    dict(deco("spookytree", "Spooky tree", [[
        "......k.....k...",
        ".k....vk...kv...",
        ".vk...vk..kv..k.",
        "..vk..vk.kv..kv.",
        "...vkkvkkv..kv..",
        "....vvVvv..kv...",
        ".kk..vVv.kkv....",
        "..vvkvVvkvv.....",
        "....vvVvvk......",
        "......vVv.......",
        "......vVv.......",
        "......vVvk......",
        ".....vvVvv......",
        "....vvVVvvv.....",
        "...vv.vVv.vv....",
        "..kk..kkk..kk...",
    ]]), set="halloween"),
    dict(deco("grave", "Gravestone", [[
        "...kkkk...",
        ".kkSSSSkk.",
        "kSSSSSSSsk",
        "kSSSkSSSsk",
        "kSSkkkSSsk",
        "kSSSkSSSsk",
        "kSSSkSSSsk",
        "kSSSSSSSsk",
        "kSSSSSSssk",
        "kSGSSSSssk",
        "kGGGssssGk",
        "kkkkkkkkkk",
    ]]), set="halloween"),
    dict(deco("cauldron", "Cauldron", [
        [
            "....l.......",
            ".......l....",
            "..l.........",
            "kkkkkkkkkkkk",
            "kGlGGlGGGlGk",
            ".kKKKKKKKKk.",
            "kKsKKKKKKKKk",
            "kKsKKKKKKKKk",
            "kKKKKKKKKKKk",
            ".kKKKKKKKKk.",
            "..kk....kk..",
        ],
        [
            ".......l....",
            "..l.........",
            ".....l...l..",
            "kkkkkkkkkkkk",
            "kGGlGGGlGGGk",
            ".kKKKKKKKKk.",
            "kKsKKKKKKKKk",
            "kKsKKKKKKKKk",
            "kKKKKKKKKKKk",
            ".kKKKKKKKKk.",
            "..kk....kk..",
        ],
    ]), set="halloween"),
]

# Things that light up at night: colour, glow radius (in art pixels), where the
# light sits inside the picture (fractions across and down), and whether it flickers.
GLOWS = {
    "lamp": ("#ffc94a", 13, (0.5, 0.28), False),
    "campfire": ("#ff8c2a", 16, (0.5, 0.45), True),
    "jack": ("#ff9a2e", 11, (0.5, 0.55), True),
    "cauldron": ("#7dff6a", 10, (0.5, 0.3), True),
    "crystal": ("#5ff0ff", 8, (0.45, 0.5), False),
    "cottage": ("#ffc94a", 8, (0.3, 0.65), False),
}


# v0.5 redraws of the original sprites (made with tools/redraw_v05.py, then
# kept here as plain data). Same ids, so saved parks pick them up.
REDRAWN = {
    "tree": [
        [
            "......................",
            "........kkkkkk........",
            ".......klllGGGk.......",
            "......klllGGGGGk......",
            ".....klllGGGGGGgk.....",
            "....kllGGGGGGGggk.....",
            "...kllGGGGGGGggglkk...",
            "..kllGGGGGGggggGGGGk..",
            ".kllGGGGGGggggGGGGGGk.",
            ".klGGGGGGgggggGGGGGgk.",
            ".kGGGGGggGGGGGGGGgggk.",
            ".kGGGGggGGGGGgGGggggk.",
            ".kGGGgggGGGGggGgggggk.",
            "..kGgggGGGGggggggggqk.",
            "...kgggGGGggggggggqk..",
            "....kkkGggggggqkkkk...",
            ".......kgggggqk.......",
            "........kkkkkk........",
            ".........kBbk.........",
            ".........kBbk.........",
            ".........kbbk.........",
            ".........kBbk.........",
            ".........kBbk.........",
            ".........kBbk.........",
            ".....kk.kkBbn.kk......",
            "......kkbBBbbnkk......",
            "......kkkkkkkkkk......",
        ],
    ],
    "pine": [
        [
            ".......kk.......",
            ".......kk.......",
            "......kGGk......",
            "......kGGk......",
            ".....kGGGgk.....",
            ".....kGGGgk.....",
            "....kGGGGggk....",
            "....kGGGgggk....",
            "...kkGGGgggkk...",
            ".....kGGggk.....",
            "....kGGGgggk....",
            "...kGGGgggggk...",
            "...kGGGgggggk...",
            "..kGGGGgggggqk..",
            "..kGGGggggggqk..",
            "...kGGgggggqk...",
            "...kGGgggggqk...",
            "..kGGggggggqqk..",
            ".kGGGgggggqqqqk.",
            ".kGGGgggggqqqqk.",
            "kkkkkkkBbkkkkkkk",
            "......kBbk......",
            "......kBbk......",
            "....kkkkkkkk....",
        ],
    ],
    "bush": [
        [
            "......kkkk......",
            ".....kllGGk.....",
            "....kllGGGGk....",
            "..kkllGGGGPgkk..",
            ".klGGPGGGggGGGk.",
            ".kGGGGGGggGGGGgk",
            "kGGGGgGgggGGPggk",
            ".kGGggggggGggggk",
            ".kkkkkkkkkkkkkk.",
            ".kkkkkkkkkkkkkk.",
        ],
    ],
    "rock": [
        [
            ".............",
            "...kkkk......",
            "..kwSSSkkkk..",
            ".kSSSSSSsssk.",
            ".kSSSSsssssk.",
            ".kSssssssKKKk",
            ".kkkkkkkkkkk.",
            ".kkkkkkkkkkk.",
        ],
    ],
    "flower": [
        [
            "..kkk..",
            ".kpPpk.",
            "kpPyPpk",
            "kpyYypk",
            ".kpPpk.",
            "..kkk..",
            "...kGk.",
            ".kkkGk.",
            "kGlGGk.",
            ".kkkGk.",
            "...kGk.",
            "..kkkkk",
        ],
    ],
    "grass": [
        [
            "....k......k.",
            "...kGk..k.kGk",
            "k..kGk.kGkkGk",
            "Gk.kGlkkGkGlk",
            "lGkGGlkGGkGGk",
            "kkkkkkkkkkkkk",
        ],
    ],
    "mushroom": [
        [
            "...........",
            "...kkkkk...",
            "..kwRRRwk..",
            ".kRRRRwRRk.",
            "kRwRRRRRrrk",
            "kkkkkkkkkkk",
            "kkkkkkkkkkk",
            "..keeeek...",
            "..keYeek...",
            "..keYeek...",
            "..keeeBk...",
            "..kkkkkk...",
        ],
    ],
    "seaweed": [
        [
            "..........",
            "kk........",
            "kCk.......",
            "kCk.......",
            ".kCk......",
            ".kCk.kkk..",
            "..kTkTk...",
            "..kTTTk...",
            "..kTTTk...",
            "..kTTTk...",
            "..kTTTtk..",
            "..kTTTtk..",
            ".kCTTTtk..",
            ".kCTTTttk.",
            ".kkkkkkkk.",
            ".kkkkkkkk.",
        ],
        [
            "..........",
            "..kk......",
            ".kCk......",
            ".kk.......",
            "kCk.......",
            "kCk....kk.",
            "kCk...ktk.",
            "kCCk..ktk.",
            ".kCk.ktk..",
            ".kCk.ktk..",
            ".kCTkTtk..",
            ".kCTTTtk..",
            ".kCTTTtk..",
            ".kCTTTtk..",
            ".kkkkkkk..",
            ".kkkkkkkk.",
        ],
    ],
    "castle": [
        [
            "...k......................",
            "...kR.....................",
            "...kRR....................",
            "kSkkSkSk..........kSkkSkSk",
            "kkkkkkkk..........kkkkkkkk",
            "kwSSSSsk..........kwSSSSsk",
            "kwSSSSsk..........kwSSSSsk",
            "kwSSSSsk.kk.kk.kk.kwSSSSsk",
            "kwSSSSskkkkkkkkkkkkwSSSSsk",
            "kwSkkSskwSSSSSSSSskwSkkSsk",
            "kwSkkSskwSSkykSSSskwSkkSsk",
            "kwSSSSskwSSkYkSSSskwSSSSsk",
            "kwSSSSskwSSSSSSSSskwSSSSsk",
            "kwSSSSskwSSSSSSSSskwSSSSsk",
            "kwSSSSskwSSSSSSSSskwSSSSsk",
            "kwSSSSskwSSkkkkSSskwSSSSsk",
            "kwSSSSskwSknnnnkSskwSSSSsk",
            "kwSSSSskwknnnnnnkskwSSSSsk",
            "kwSSSSskwknnyynnkskwSSSSsk",
            "kwSSSSskwknnnnnnkskwSSSSsk",
            "kwSSSSskwknnnnnnkskwSSSSsk",
            "kkkkkkkkkkkkkkkkkkkkkkkkkk",
            "kkkkkkkkkkkkkkkkkkkkkkkkkk",
        ],
    ],
    "cottage": [
        [
            "...........kRpk...........",
            "..........kRpppk..kkk.....",
            "........kkRpppRpkkkKk.....",
            ".......kpRpppRpppRkKk.....",
            "......kpRpppRpppRppk......",
            ".....kRrRRRRpppRpppRk.....",
            "...kkRrRRRrRRRrRppRppkk...",
            "..kRRrRRRrRRRrRRRrRRRRpk..",
            ".kRRrRRRrRRRrRRRrRRRrRRRk.",
            "kkkkkkkkkkkkkkkkkkkkkkkkkk",
            "...kkkkkkkkkkkkkkkkkkkk...",
            "...kYeeeeeeeeeeeeeeeeBk...",
            "...kYekkkkkeeeeeeeeeeBk...",
            "...kYekcCckeeeekkkkkeBk...",
            "...kYekkkkkeeeekBbBkeBk...",
            "...kYekcCckeeeekBbBkeBk...",
            "...kYekkkkkeeeekBBykeBk...",
            "...kYeeeeeeeeeekBbBkeBk...",
            "...kYeeeeeeeeeekBbBkeBk...",
            "...kYeeeeeeeeeekBbBkeBk...",
            "...kkkkkkkkkkkkkkkkkkkk...",
            "..kkkkkkkkkkkkkkkkkkkkkk..",
        ],
    ],
    "fish": [
        [
            "....kkkkk....",
            "kk.kOyyyOk...",
            "kOkOyyOOOOkk.",
            "kOOOOOOOOwkOk",
            "kOkOOOOOOOkk.",
            "kk.kBBBBBk...",
            "....kkkkk....",
        ],
        [
            "....kkkkk....",
            "...kOyyyOk...",
            "kkkOyyOOOOkk.",
            "kOOOOOOOOwkOk",
            "kkkOOOOOOOkk.",
            "...kBBBBBk...",
            "....kkkkk....",
        ],
        [
            "....kkkkk....",
            "...kOyyyOk...",
            "k.kOyyOOOOkk.",
            "kOkOOOOOOwkOk",
            "kOOOOOOOOOkk.",
            "kk.kBBBBBk...",
            "....kkkkk....",
        ],
    ],
    "slime": [
        [
            "............",
            "............",
            "...kkkkkk...",
            "..kwlGGGGk..",
            ".kwGGGGkGkk.",
            ".kGGGGGkGkk.",
            "kGGGGGGGGggk",
            "kGGGGGGggggk",
            "kkkkkkkkkkkk",
            ".kkkkkkkkkk.",
        ],
        [
            "............",
            "............",
            "............",
            "...kkkkkk...",
            "..klGGGGGk..",
            ".kGGGGGkGkk.",
            "kGGGGGGkGkgk",
            "kGGGGGGggggk",
            "kkkkkkkkkkkk",
            ".kkkkkkkkkk.",
        ],
    ],
    "cat": [
        [
            "..........k...k.",
            "..........kk.kk.",
            "k.........kOOOOk",
            "kOk.......kOkOkk",
            ".kOk.kkkkkkyOpOk",
            "..kOOOOOOOOOOkk.",
            "..kOyyOOOOOOBk..",
            "..kOOOOOOOOBBk..",
            "...kOk.kOk.kOk..",
            "...kk..kk..kk...",
        ],
        [
            "..........k...k.",
            "..........kk.kk.",
            "..........kOOOOk",
            "k.........kOkOkk",
            "kOk..kkkkkkyOpOk",
            "..kOOOOOOOOOOkk.",
            "..kOyyOOOOOOBk..",
            "..kOOOOOOOOBBk..",
            "..kOk..kOk..kOk.",
            "..kk...kk....kk.",
        ],
    ],
    "bird": [
        [
            "...kk.......",
            "..kcUk......",
            "..kUcUk.kk..",
            "...kUUkkUUk.",
            "..kUUUUUUwkk",
            ".kUcccUUUkyy",
            "kUUUUUUUUk..",
            ".kkkkkkkkk..",
            "....kk.kk...",
        ],
        [
            "............",
            "............",
            "........kk..",
            ".......kUUk.",
            "..kkkkkUUwkk",
            ".kUcccUUUkyy",
            "kUUkUUUUUk..",
            ".kUUUkkkkk..",
            "..kkk.kk....",
        ],
    ],
    "butterfly": [
        [
            ".kk.....kk.",
            "kmVk...kVmk",
            "kVmVk.kVmVk",
            ".kVVkkkVVk.",
            "..kmVkVmk..",
            "..kVk.kVk..",
            "...k...k...",
        ],
        [
            "...........",
            "....k.k....",
            "...kVkVk...",
            "...kmkmk...",
            "...kVkVk...",
            "....k.k....",
            "...........",
        ],
    ],
    "lamp": [
        [
            "..kkk..",
            ".kKKKk.",
            "kYyYyYk",
            "kyYYYyk",
            ".kkkkk.",
            "..kKk..",
            "..kKk..",
            "..kKk..",
            "..kKk..",
            "..kKk..",
            "..kKk..",
            ".kKKKk.",
            "kkkkkkk",
        ],
    ],
}


def _lift(sprite_id, mapping):
    """v0.5 readability: lighter body colours for the darkest Halloween sprites."""
    table = str.maketrans(mapping)
    for a in HALLOWEEN:
        if a["id"] == sprite_id:
            a["frames"] = [[row.translate(table) for row in f] for f in a["frames"]]


_lift("bat", {"v": "V", "V": "m"})
_lift("cauldron", {"K": "s", "s": "S"})
