"""More built-in art, all on one shared palette (see the pixel-art skill).

Letters: k outline, K/s/S/w greys to white, q/g/G/l greens, n/b/B/e browns,
r/R/p/P reds to pink, O orange, y/Y yellows, u/U/c/C blues, v/V/m purples,
t/T teals. "." is see-through. Everything faces right.
"""

PAL = {
    "k": "#1a1c2c", "K": "#333c57", "s": "#566c86", "S": "#94b0c2", "w": "#f4f4f4",
    "q": "#1e4a3a", "g": "#257953", "G": "#38b764", "l": "#a7f070",
    "n": "#3d2a24", "b": "#6e4a30", "B": "#a8703c", "e": "#e8c48c",
    "r": "#8c2a3a", "R": "#d6404e", "p": "#ff8a9a", "P": "#ffcdd2",
    "O": "#ef7d3a", "y": "#ffcd4f", "Y": "#fff1a8",
    "u": "#29366f", "U": "#3b5dc9", "c": "#41a6f6", "C": "#73eff7",
    "v": "#4b2a6b", "V": "#8a4fc0", "m": "#d69cf2",
    "t": "#1f6f73", "T": "#3fb8a8",
}


def pet(id, name, behavior, frames, speed=1.0):
    return {"id": id, "name": name, "kind": "pet", "behavior": behavior,
            "palette": PAL, "frames": frames, "speed": speed}


def deco(id, name, frames, behavior="stay"):
    return {"id": id, "name": name, "kind": "deco", "behavior": behavior,
            "palette": PAL, "frames": frames}


PACK = [
    # ---------------------------------------------------------------- pets
    pet("bunny", "Bunny", "hop", [
        [
            "......k.k...",
            ".....kpkpk..",
            ".....kpkpk..",
            ".....kwkwk..",
            "....kwwwwwk.",
            "....kwwwkwwk",
            ".kk.kwwwwwpk",
            "kwwkkwwwwwk.",
            "kwwwwwwwwk..",
            "kSwwwwwwSk..",
            ".kSSwwSSk...",
            "..kkkkkkk...",
        ],
        [
            "......k.k...",
            ".....kpkpk..",
            ".....kpkpk..",
            ".....kwkwk..",
            "....kwwwwwk.",
            "....kwwwkwwk",
            ".kk.kwwwwwpk",
            "kwwkkwwwwwk.",
            "kwwwwwwwwk..",
            "kSwwwwwwSk..",
            "kSSk.kSSk...",
            "kkk..kkk....",
        ],
    ]),
    pet("frog", "Frog", "hop", [
        [
            "...kkk.kkk..",
            "..kwwkGkwwk.",
            "..kwkkGkwkk.",
            ".kGGGGGGGGk.",
            "kGlGGGGGGGGk",
            "kGGGGGGRRRGk",
            "kgGGGGGGGGgk",
            "kgYYYYYYYYgk",
            ".kggk..kggk.",
            "kkkk....kkkk",
        ],
        [
            "............",
            "...kkk.kkk..",
            "..kwwkGkwwk.",
            "..kwkkGkwkk.",
            ".kGGGGGGGGk.",
            "kGlGGGGGGGGk",
            "kGGGGGGRRRGk",
            "kgGYYYYYYGgk",
            "kgkk....kkgk",
            "kk........kk",
        ],
    ]),
    pet("duck", "Duck", "walk", [
        [
            "......kkkk..",
            ".....kyyyyk.",
            ".....kyykyk.",
            ".....kyyyyOO",
            "k....kyyyyk.",
            "kk..kyyyyk..",
            "kykkyyyyyyk.",
            "kyyyyYYyyyk.",
            ".kyyYYYYyk..",
            "..kkkkkkk...",
            "....kO.kO...",
            "...kOO.kOO..",
        ],
        [
            "......kkkk..",
            ".....kyyyyk.",
            ".....kyykyk.",
            ".....kyyyyOO",
            "k....kyyyyk.",
            "kk..kyyyyk..",
            "kykkyyyyyyk.",
            "kyyyyYYyyyk.",
            ".kyyYYYYyk..",
            "..kkkkkkk...",
            ".....kOkO...",
            "....kOOkOO..",
        ],
    ]),
    pet("chick", "Chick", "walk", [
        [
            "...kkkk..",
            "..kYYYYk.",
            ".kYYYkYk.",
            ".kYYYYYOO",
            "kYYYyYYk.",
            "kYYyyYYk.",
            "kYYYYYYk.",
            ".kkkkkk..",
            "..O..O...",
        ],
        [
            "...kkkk..",
            "..kYYYYk.",
            ".kYYYkYk.",
            ".kYYYYYOO",
            "kYYYyYYk.",
            "kYYyyYYk.",
            "kYYYYYYk.",
            ".kkkkkk..",
            "...O.O...",
        ],
    ], speed=0.8),
    pet("dog", "Dog", "walk", [
        [
            "..........kk....",
            ".........kbbkk..",
            ".........kBBBBk.",
            "k........kBkBBBk",
            "kBk......kBBBBkk",
            ".kBk.kkkkbBBBBk.",
            "..kkBBBBBBBkkk..",
            "..kBBeeeeBBk....",
            "..kBBBBBBBBk....",
            "..kBk.kBk.kBk...",
            "..kk..kk..kk....",
        ],
        [
            "..........kk....",
            ".........kbbkk..",
            ".........kBBBBk.",
            ".........kBkBBBk",
            "k........kBBBBkk",
            "kBk..kkkkbBBBBk.",
            ".kkkBBBBBBBkkk..",
            "..kBBeeeeBBk....",
            "..kBBBBBBBBk....",
            ".kBk..kBk..kBk..",
            ".kk...kk...kk...",
        ],
    ]),
    pet("penguin", "Penguin", "walk", [
        [
            "...kkkk...",
            "..kKKKKk..",
            ".kKKwKwKk.",
            ".kKKwwwOO.",
            "kKKwwwwwk.",
            "kKkwwwwwk.",
            "kKkwwwwwk.",
            "kKKwwwwwk.",
            ".kKwwwwk..",
            "..kkkkk...",
            "..OO.OO...",
        ],
        [
            "...kkkk...",
            "..kKKKKk..",
            ".kKKwKwKk.",
            ".kKKwwwOO.",
            "kKKwwwwwk.",
            "kKKkwwwwk.",
            "kKKkwwwwk.",
            "kKKwwwwwk.",
            ".kKwwwwk..",
            "..kkkkk...",
            ".OO...OO..",
        ],
    ], speed=0.6),
    pet("crab", "Crab", "walk", [
        [
            ".kk......kk.",
            "kRRk....kRRk",
            "kRk......kRk",
            ".kRk.kk.kRk.",
            "..kkwkkwkk..",
            ".kRRRRRRRRk.",
            "kRpRRRRRRRRk",
            "kRRRRRRRRRRk",
            ".krrrrrrrrk.",
            "k.k.k..k.k.k",
        ],
        [
            ".kk......kk.",
            "kRRk....kRRk",
            "kRk......kRk",
            ".kRk.kk.kRk.",
            "..kkwkkwkk..",
            ".kRRRRRRRRk.",
            "kRpRRRRRRRRk",
            "kRRRRRRRRRRk",
            ".krrrrrrrrk.",
            ".k.k.kk.k.k.",
        ],
    ], speed=0.7),
    pet("turtle", "Turtle", "walk", [
        [
            "....kkkkk.......",
            "...kgGGGgk......",
            "..kgGlGGGgk.kkk.",
            ".kgGGGgGGGgkGGGk",
            ".kgGGgGgGGgkGkGk",
            "kggggggggggkGGGk",
            "kkkkkkkkkkkkkkk.",
            ".kGGk....kGGk...",
            ".kkk.....kkk....",
        ],
        [
            "....kkkkk.......",
            "...kgGGGgk......",
            "..kgGlGGGgk.kkk.",
            ".kgGGGgGGGgkGGGk",
            ".kgGGgGgGGgkGkGk",
            "kggggggggggkGGGk",
            "kkkkkkkkkkkkkkk.",
            "..kGGk..kGGk....",
            "..kkk...kkk.....",
        ],
    ], speed=0.35),
    pet("snail", "Snail", "walk", [
        [
            "...kkkk.......",
            "..kVmmVk..k.k.",
            ".kVmVVmVk.kek.",
            ".kVmkVmVk.kek.",
            ".kVmVVmVk.keek",
            "..kVVVVkkeekek",
            "kkeeeeeeeeeek.",
            "keeeeeeeeeek..",
            ".kkkkkkkkkk...",
        ],
        [
            "...kkkk.......",
            "..kVmmVk...k.k",
            ".kVmVVmVk..kek",
            ".kVmkVmVk.keek",
            ".kVmVVmVk.keek",
            "..kVVVVkkeekek",
            "keeeeeeeeeeek.",
            "keeeeeeeeeek..",
            ".kkkkkkkkkk...",
        ],
    ], speed=0.25),
    pet("bee", "Bee", "fly", [
        [
            "...kk.kk...",
            "..kCCkCCk..",
            "..kCCkCCk..",
            ".kkykkkykk.",
            "kyykyykyykk",
            "kyykyykykwk",
            "kyykyykyyk.",
            ".kkkkkkkk..",
        ],
        [
            "...........",
            "...........",
            "..kkk.kkk..",
            ".kCCkkkCCk.",
            "kyykyykyykk",
            "kyykyykykwk",
            "kyykyykyyk.",
            ".kkkkkkkk..",
        ],
    ]),
    pet("butterfly", "Butterfly", "fly", [
        [
            ".kkk...kkk.",
            "kmVVk.kVVmk",
            "kVmmVkVmmVk",
            "kVVmVkVmVVk",
            ".kVVkkkVVk.",
            ".kmVkkkVmk.",
            ".kVVk.kVVk.",
            "..kk...kk..",
        ],
        [
            "...........",
            "...........",
            "..kk...kk..",
            ".kmVk.kVmk.",
            ".kVmVkVmVk.",
            "..kVkkkVk..",
            "...kkkkk...",
            "...........",
        ],
    ], speed=0.7),
    pet("ghost", "Ghost", "swim", [
        [
            "...kkkk...",
            "..kwwwwk..",
            ".kwwwwwwk.",
            ".kwwkwkwk.",
            "kwwwwwwwwk",
            "kwwwwwPwwk",
            "kSwwwwwwwk",
            "kSSwwwwwSk",
            "kSkSwSkSSk",
            "kk.kk.kk.k",
        ],
        [
            "...kkkk...",
            "..kwwwwk..",
            ".kwwwwwwk.",
            ".kwwkwkwk.",
            "kwwwwwwwwk",
            "kwwwwwPwwk",
            "kSwwwwwwwk",
            "kSSwwwwwSk",
            "kSSkSwSkSk",
            "k.kk.kk.kk",
        ],
    ], speed=0.6),
    pet("jelly", "Jellyfish", "swim", [
        [
            "...kkkk...",
            "..kmmmmk..",
            ".kmPmmmmk.",
            "kmPmmmmmmk",
            "kmmmmmmmmk",
            "kkkkkkkkkk",
            ".m.m..m.m.",
            ".m..m.m..m",
            "m..m..m.m.",
            ".m.m...m..",
        ],
        [
            "..........",
            "...kkkk...",
            "..kmmmmk..",
            ".kmPmmmmk.",
            "kmPmmmmmmk",
            "kkkkkkkkkk",
            "m.m..m.m..",
            ".m.m.m..m.",
            ".m..m.m..m",
            "m...m..m..",
        ],
    ], speed=0.5),
    pet("puffer", "Pufferfish", "swim", [
        [
            "...k.k.k...",
            "..kykykyk..",
            ".kyyyyyyyk.",
            "kyyYYyywkyk",
            "kyYYyyykkyk",
            "kyyyyyyyyyO",
            "kyyyYYYyyyk",
            ".kyyyyyyyk.",
            "..kykykyk..",
            "...k.k.k...",
        ],
        [
            "...........",
            "...k.k.k...",
            "..kykykyk..",
            "kkyyyyywkyk",
            "kyYYyyykkyk",
            "kyyyyyyyyyO",
            "kkyyYYYyyyk",
            "..kykykyk..",
            "...k.k.k...",
            "...........",
        ],
    ], speed=0.6),

    # -------------------------------------------------------------- decor
    deco("cactus", "Cactus", [[
        ".....kk.....",
        "....kGlk....",
        "....kGGk....",
        ".kk.kGlk....",
        "kGGkkGGk.kk.",
        "kGlkkGlkkGGk",
        "kGGGGGGkkGlk",
        ".kkkkGlGGGGk",
        "....kGGkkkk.",
        "....kGlk....",
        "..kkkkkkkk..",
        "..kBBBBBBk..",
        "...kbbbbk...",
        "...kkkkkk...",
    ]]),
    deco("sunflower", "Sunflower", [[
        "...kkkk...",
        "..kyYYyk..",
        ".kyybbyyk.",
        "kyYbnnbyyk",
        "kyybnnbyyk",
        ".kyybbyyk.",
        "..kyyyyk..",
        "...kkGk...",
        ".kk.kGk...",
        "kGlkkGk...",
        ".kGGGGk.kk",
        "....kGkkGk",
        "....kGGGk.",
        "....kGk...",
        "....kgk...",
    ]]),
    deco("tulips", "Tulips", [[
        ".k.k...k.k..",
        "kRkRk.kmkmk.",
        "kRRRk.kmmmk.",
        ".kRk...kmk..",
        "..G..k..G...",
        "..G.kyk.G...",
        "..GGkYkGG...",
        ".lGG.G.Gl...",
        "..G..G.G....",
        ".kkkkkkkkkk.",
    ]]),
    deco("stump", "Stump", [[
        "..kkkkkkk...",
        ".keBBeeBek..",
        "keBeeBBeeBk.",
        "kbeBBBBBebk.",
        "kbkeeeeekbk.",
        "kbbbBbbbbbk.",
        "kbbBbbbBbbk.",
        "kbbBbbbBbbkk",
        "kbbbbbBbbbbk",
        "knnnnnnnnnnk",
    ]]),
    deco("fence", "Fence", [[
        "..k......k......",
        ".kek....kek.....",
        ".kek....kek.....",
        "kkekkkkkkekkkkkk",
        "eeeeeeeeeeeeeeee",
        "kkBkkkkkkBkkkkkk",
        ".kek....kek.....",
        "kkekkkkkkekkkkkk",
        "eeeeeeeeeeeeeeee",
        "kkBkkkkkkBkkkkkk",
        ".kek....kek.....",
        ".kBk....kBk.....",
    ]]),
    deco("sign", "Signpost", [[
        "kkkkkkkkkkk.",
        "keeeeeeeeeek",
        "keBBkBkBBek.",
        "keeeeeeeeeek",
        "kBBBBBBBBBk.",
        "kkkkkbkkkkk.",
        ".....bk.....",
        ".....bk.....",
        ".....bk.....",
        "....kbbk....",
    ]]),
    deco("campfire", "Campfire", [
        [
            ".....k......",
            "....kRk.....",
            "...kROk.k...",
            "...kOyRkRk..",
            "..kROyyORk..",
            "..kOyYYyOk..",
            "..kOyYYyOk..",
            ".kkbkOOkbkk.",
            "kBbbBkkBbbBk",
            "ksskkBBkkssk",
            ".kkkkkkkkkk.",
        ],
        [
            "......k.....",
            ".....kRk....",
            "..k..kORk...",
            ".kRk.kROk...",
            "..kROyyORk..",
            "..kOyYyyOk..",
            "..kOyYYyOk..",
            ".kkbkOOkbkk.",
            "kBbbBkkBbbBk",
            "ksskkBBkkssk",
            ".kkkkkkkkkk.",
        ],
    ]),
    deco("lamp", "Lamp post", [[
        "...kkk...",
        "..kKKKk..",
        ".kKKKKKk.",
        ".kYyYyYk.",
        ".kyYYYyk.",
        ".kYyYyYk.",
        "..kkkkk..",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "...kKk...",
        "..kKKKk..",
        ".kKKKKKk.",
    ]]),
    deco("cherry", "Cherry tree", [[
        ".....kkkkk......",
        "...kkPPpPPkk....",
        "..kPPwPPPPpPk...",
        ".kPwPPPpPPPPPk..",
        ".kPPPPPPPwPPpk..",
        "kpPPpPPPPPPPPPk.",
        "kPPPPPwPPpPPPPk.",
        "kpPPPPPPPPPPPpk.",
        ".kppPPPpPPPPpk..",
        "..kkppkbkppkk...",
        "....kkkbkk......",
        "......kbbk......",
        "......kbbk......",
        "......kbbk......",
        ".....kbbbbk.....",
        "....kbbkkbbk....",
    ]]),
    deco("palm", "Palm tree", [[
        ".....kkkk.......",
        "...kkGGGGkkk....",
        "..kGGlGGGGGGk...",
        ".kGGkkGGkkGGGk..",
        "kGGk..kBBkkkGGk.",
        "kGk...kBk...kGk.",
        "kk....kBk....kk.",
        ".......kBk......",
        ".......kBk......",
        "........kBk.....",
        "........kBk.....",
        "........kBk.....",
        ".......kBBk.....",
        "......kBbBBk....",
    ]]),
    deco("coral", "Coral", [[
        "..k.....k...",
        ".kpk...kpk..",
        ".kpk.k.kpk.k",
        ".kpkkpkkpkkp",
        "k.kpkpkpkkpk",
        "kpkpkpkpk.kp",
        ".kpppppkkpk.",
        "..kpRRpppk..",
        "...kRRRpk...",
        "....kRRk....",
        "..kkkRRkkk..",
    ]]),
    deco("chest", "Treasure chest", [[
        "..kkkkkkkkk...",
        ".kBBBBBBBBBk..",
        "kBByyyyyyyBBk.",
        "kBBBBBBBBBBBk.",
        "kkkkkkykkkkkk.",
        "kbBBBkYykBBbk.",
        "kbBBBkkkBBBbk.",
        "kbBBBBBBBBBbk.",
        "knnnnnnnnnnnk.",
        ".kkkkkkkkkkk..",
    ]]),
    deco("crystal", "Crystals", [[
        ".....k......",
        "....kCk.....",
        "...kCwck....",
        "...kCcck....",
        ".k.kCcck.k..",
        "kCkkCccckmk.",
        "kCwkCcckVmk.",
        "kcckCccckVmk",
        "kcckcuucVVVk",
        "kkkkkkkkkkkk",
    ]]),
    deco("pumpkin", "Pumpkin", [[
        ".....kk.....",
        "....kgk.....",
        "..kkkkkkkk..",
        ".kOyOkOOyOk.",
        "kOyOOkOyOOOk",
        "kOyOOkOyOOOk",
        "kOOOOkOOOOOk",
        "kOOOrkOOOOrk",
        ".krrrkrrrrk.",
        "..kkkkkkkk..",
    ]]),
    deco("cottage", "Cottage", [[
        "............kkk...",
        "......kk....kKk...",
        "....kkRRkk..kKk...",
        "..kkRRRRRRkkkKk...",
        ".kRRRRRRRRRRRkk...",
        "kRRRRRRRRRRRRRRk..",
        "krrrrrrrrrrrrrrrk.",
        ".keeeeeeeeeeeek...",
        ".keUUkeeeekBBkek..",
        ".kecCkeeeekBBkek..",
        ".keeeeeeeekBBkek..",
        ".keeeeeeeekByBek..",
        ".kBBBBBBBBkBBkBk..",
        ".kkkkkkkkkkkkkkk..",
    ]]),
    deco("cloud", "Cloud", [[
        ".....kkkk.......",
        "...kkwwwwkk.....",
        "..kwwwwwwwwkkk..",
        ".kwwwwwwwwwwwwk.",
        "kwwwwwwwwwwwwwwk",
        "kSwwwwwwwwwwwwSk",
        ".kSSSwwwwwwSSSk.",
        "..kkkkkkkkkkkk..",
    ]], behavior="stay"),
    deco("pond", "Pond", [[
        "....kkkkkkkk....",
        "..kkcCccccCcckk.",
        ".kcCccGkcccccCck",
        "kcccckGGkcwccccck"[:16],
        "kcccUccccccccUck",
        ".kUcccccUccccUk.",
        "..kkUUUUUUUUkk..",
        "....kkkkkkkk....",
    ]]),
]
